# Generated by Django 5.1.4 on 2024-12-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('eMail', models.CharField(max_length=100, verbose_name='eMail')),
                ('UserType', models.CharField(max_length=100, verbose_name='User Type')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
