# Generated by Django 5.1.4 on 2025-01-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='UserType',
            new_name='user_type',
        ),
    ]
