# Generated by Django 5.1.4 on 2024-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
