# Generated by Django 5.1.4 on 2024-12-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0002_userlist_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerPic', models.ImageField(upload_to='bannerpic')),
            ],
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='banner',
        ),
    ]
