# Generated by Django 5.1.4 on 2025-01-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0002_rename_usertype_userlist_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='ProjectLTs',
            new_name='project_lts',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='ProjectManager',
            new_name='project_manager',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='ProjectName',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='ProjectTesters',
            new_name='project_testers',
        ),
    ]
