# Generated by Django 5.1.4 on 2024-12-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0003_bannerphoto_remove_userlist_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerPhoto',
        ),
    ]
