# Generated by Django 5.1.4 on 2025-01-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0004_alter_projects_active_alter_projects_project_lts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='on_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KPITracker.projects'),
        ),
    ]
