# Generated by Django 5.1.4 on 2025-01-01 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0004_delete_bannerphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100, verbose_name='Project Name')),
                ('ProjectManager', models.CharField(max_length=100, verbose_name='Project Manager')),
                ('ProjectLTs', models.JSONField()),
                ('ProjectTesters', models.JSONField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userlist',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
