# Generated by Django 5.1.4 on 2025-01-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0005_projects_userlist_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='username',
            new_name='Username',
        ),
    ]
