# Generated by Django 5.1.4 on 2025-01-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0006_rename_username_userlist_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='active',
            new_name='Active',
        ),
        migrations.AddField(
            model_name='userlist',
            name='DateJoined',
            field=models.TimeField(default='admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlist',
            name='Password',
            field=models.CharField(default='admin', max_length=100, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='SuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
