# Generated by Django 5.1.4 on 2025-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0006_remove_projects_project_lts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_activity',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Activity'),
        ),
    ]
