# Generated by Django 5.1.4 on 2025-01-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0007_projects_project_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='on_project',
        ),
        migrations.AddField(
            model_name='userlist',
            name='on_project_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Assigned Project ID'),
        ),
    ]
