# Generated by Django 5.1.4 on 2025-01-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0008_remove_userlist_on_project_userlist_on_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='on_project_id',
        ),
        migrations.AddField(
            model_name='userlist',
            name='on_project',
            field=models.CharField(max_length=100, null=True, verbose_name='Assigned Project'),
        ),
    ]
