# Generated by Django 5.1.4 on 2025-01-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0009_remove_userlist_on_project_id_userlist_on_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='active',
            field=models.BooleanField(verbose_name='Ongoing'),
        ),
    ]
