# Generated by Django 5.1.4 on 2025-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0011_projects_reopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_partner',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Partner'),
        ),
    ]
