# Generated by Django 5.1.4 on 2025-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0012_projects_project_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='on_project',
            field=models.CharField(default='None', max_length=100, verbose_name='Assigned Project'),
        ),
    ]
