# Generated by Django 5.1.4 on 2025-01-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0014_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Project Description'),
        ),
    ]
