# Generated by Django 5.1.4 on 2025-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0016_remove_projects_reopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='gross_salary',
            field=models.CharField(max_length=100, null=True, verbose_name='Gross Salary'),
        ),
    ]
