# Generated by Django 5.1.4 on 2025-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0017_userlist_gross_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Location Name')),
                ('lat', models.CharField(max_length=200, null=True, verbose_name='Latitude')),
                ('lon', models.CharField(max_length=200, null=True, verbose_name='Longitude')),
                ('country', models.CharField(max_length=200, null=True, verbose_name='Country')),
                ('region', models.CharField(max_length=200, null=True, verbose_name='Region')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='City')),
                ('street', models.CharField(max_length=200, null=True, verbose_name='Street')),
                ('number', models.CharField(max_length=200, null=True, verbose_name='Number')),
                ('zipcode', models.IntegerField(null=True, verbose_name='Number')),
            ],
        ),
        migrations.AddField(
            model_name='userlist',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='work_location',
            field=models.CharField(max_length=200, null=True, verbose_name='Work Location'),
        ),
    ]
