# Generated by Django 5.1.4 on 2025-02-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0019_countrycodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryCodes',
        ),
    ]
