# Generated by Django 5.1.4 on 2025-02-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0020_delete_countrycodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, verbose_name='Country Code')),
            ],
        ),
    ]
