# Generated by Django 5.1.4 on 2025-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0023_countrycodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
