# Generated by Django 5.1.4 on 2025-02-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0024_alter_userlist_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryCodes',
        ),
    ]
