# Generated by Django 5.1.4 on 2025-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0025_delete_countrycodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsregistered',
            name='misc_description',
            field=models.CharField(max_length=800, null=True, verbose_name='Misc Description'),
        ),
    ]
