# Generated by Django 5.1.4 on 2025-02-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0026_locationsregistered_misc_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationsRegistered',
        ),
    ]
