# Generated by Django 5.1.4 on 2025-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0028_locationsregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsregistered',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Location Name'),
        ),
    ]
