# Generated by Django 5.1.4 on 2025-02-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0029_alter_locationsregistered_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('critical_issues', models.IntegerField(default=0, verbose_name='Critical Issues')),
                ('major_issues', models.IntegerField(default=0, verbose_name='Major Issues')),
                ('medium_issues', models.IntegerField(default=0, verbose_name='Medium Issues')),
                ('minor_issues', models.IntegerField(default=0, verbose_name='Minor Issues')),
                ('test_cases_started', models.IntegerField(default=0, verbose_name='Started Test Cases')),
                ('test_cases_passed', models.IntegerField(default=0, verbose_name='Passed Test Cases')),
                ('test_cases_partially_passed', models.IntegerField(default=0, verbose_name='Partially Passed Test Cases')),
                ('test_cases_failed', models.IntegerField(default=0, verbose_name='Failed Test Cases')),
                ('test_cases_blocked', models.IntegerField(default=0, verbose_name='Unable to Check Test Cases')),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='KPITracker.userlist')),
            ],
        ),
    ]
