# Generated by Django 5.1.4 on 2025-02-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0030_kpireport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KPIReport',
        ),
    ]
