# Generated by Django 5.1.4 on 2025-02-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0038_kpireport'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpireport',
            name='task',
            field=models.CharField(max_length=200, null=True, verbose_name='Allocated Task'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ongoing'),
        ),
    ]
