# Generated by Django 5.1.4 on 2025-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0039_kpireport_task_alter_projects_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpireport',
            name='report_observations',
            field=models.CharField(max_length=2000, null=True, verbose_name='Observations'),
        ),
    ]
