# Generated by Django 5.1.4 on 2025-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0040_kpireport_report_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpireport',
            name='optional_issues',
            field=models.IntegerField(default=0, verbose_name='Optional Issues'),
        ),
    ]
