# Generated by Django 5.1.4 on 2025-02-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPITracker', '0041_kpireport_optional_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpireport',
            name='report_observations',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='locationsregistered',
            name='misc_description',
            field=models.TextField(blank=True, null=True, verbose_name='Misc Description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description'),
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Task Name')),
                ('assigned_testers', models.TextField(blank=True, verbose_name='Assigned testers')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='KPITracker.projects')),
            ],
        ),
    ]
